In [6]:
import numpy as np

NUMPY

numpy>>>>>lists
- fixed datatypes 
- requires less space (bytes of memory)
- no typechecking when interating through objects 
- uses contiguous memory locations
(lists arent necessarily having  contiguous memory locations)
- effective cache utilization

application: 
- mathematics  (MATLAB replacement) 
- plotting(matplotlib)
- backend( pandas , connect 4 , digital photography)
- machine learning domain

* how install it
==> pip install numpy

NumPy (Numerical Python) is a powerful Python library for numerical and scientific computing.
It provides:

N-dimensional array object (ndarray)

Tools for mathematical operations (like linear algebra, stats)

Functions for random number generation

Easy integration with C/C++/Fortran

Efficient memory handling and vectorization

Why use NumPy over regular Python lists?
Much faster (thanks to C-level optimizations)

Uses less memory

Easier and more powerful for mathematical operations

Supports broadcasting (applying operations across arrays of different shapes)





### 🔧 **Topic 3: Applications of NumPy**

NumPy is foundational in the Python **scientific computing ecosystem**. It’s used widely in:

---

#### 📊 **1. Data Analysis**

* Libraries like **pandas** are built on top of NumPy.
* All tabular data manipulations (filtering, grouping, statistics) rely on fast NumPy operations under the hood.

---

#### 📷 **2. Image Processing**

* Images are just arrays of pixels. Libraries like **OpenCV**, **Pillow**, and **scikit-image** use NumPy arrays to store and manipulate images:

  ```python
  import cv2
  img = cv2.imread('image.jpg')  # shape: (height, width, 3)
  print(img.shape)
  ```

---

#### 🧠 **3. Machine Learning & Deep Learning**

* **Scikit-learn**, **TensorFlow**, and **PyTorch** all use NumPy internally.
* Model inputs (features) and outputs (labels) are represented as arrays.

---

#### 📈 **4. Data Visualization**

* Libraries like **matplotlib**, **seaborn**, and **plotly** rely on NumPy to efficiently handle large datasets during plotting.

---

#### 🔬 **5. Scientific Simulations**

* Used in physics, chemistry, biology, and finance for simulations, numerical methods, etc.

---

#### 🧮 **6. Linear Algebra & Statistics**

* NumPy offers efficient implementations of:

  * Matrix multiplication
  * Eigenvalues & eigenvectors
  * Mean, median, standard deviation, correlation, etc.

In [45]:
import numpy as np
import time

# Python list
list1 = list(range(1000000))
start = time.time()
list_sum = [x + 1 for x in list1]
end = time.time()
print("List time:", end - start)

# NumPy array
arr = np.arange(1000000)
start = time.time()
arr_sum = arr + 1
end = time.time()
print("NumPy time:", end - start)


List time: 0.12238788604736328
NumPy time: 0.00447392463684082


In [ ]:
🔧 Functionality
NumPy supports vectorized operations:

In [46]:
arr = np.array([1, 2, 3])
print(arr * 2)  # Output: [2 4 6]


[2 4 6]


Lists require a loop for the same:

In [47]:
lst = [1, 2, 3]
print([x * 2 for x in lst])


[2, 4, 6]


Result: NumPy will be multiple times faster.

In [20]:
a=np.array([1,2,4], dtype="int16")
a

array([1, 2, 4], dtype=int16)

In [12]:
b=np.array([[1.2,4.5,8.9],[1,2,3]])
print(b)

[[1.2 4.5 8.9]
 [1.  2.  3. ]]


In [16]:
b.ndim # get no of dimensions


2

In [18]:
b.shape # get size or shape of array

(2, 3)

In [21]:
a.dtype # get datatype

dtype('int16')

In [22]:
a.itemsize # varies based on int32 or int16

2

In [23]:
a.size

3

In [24]:
a.nbytes # or a.itemsize * a.size

6

In [26]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [51]:
# get a specific element
a = np.array([[1, 2, 3], [4, 5, 6]])
a[1, 1] = 99
a

array([[ 1,  2,  3],
       [ 4, 99,  6]])

In [52]:
import numpy as np
a = np.array([[10,11,12,13],
              [20,21,22,23],
              [30,31,32,33],
              [40,41,42,43]])

print(a[:3, ::2])


[[10 12]
 [20 22]
 [30 32]]


In NumPy 2D arrays, slicing follows this format:

a[row_start:row_stop:row_step, col_start:col_stop:col_step]

Before the comma → for rows
After the comma → for columns

In [54]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(a[0:3:2, 0:3:2])

[[10 30]
 [70 90]]


1. Creating an Array of Zeros
You can create an array filled with zeros using np.zeros(shape):

2. Creating an Array of Ones
To create an array filled with ones, use np.ones(shape):

In [57]:
print(np.zeros((3, 3)))# 3x3 array of zeros
print()
print(np.ones((2, 4)))  # 2x4 array of ones


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Creating an Array with a Specific Value
You can create an array filled with a specific value using np.full(shape, fill_value):

In [58]:
a=np.full((2, 3), 7)  # 2x3 array filled with 7
a

array([[7, 7, 7],
       [7, 7, 7]])

4. Creating an Identity Matrix
An identity matrix has 1s on the diagonal and 0s elsewhere. Use np.eye(n):

In [59]:
np.eye(4)  # 4x4 identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

5. Creating a Random Array
You can generate random arrays with numbers from a uniform distribution between 0 and 1 using np.random.rand():

In [60]:
np.random.rand(3, 2)  # 3x2 random array


array([[0.94556474, 0.72813345],
       [0.10256866, 0.26424028],
       [0.89099448, 0.23802723]])

6. Creating a Sequence of Numbers (using np.arange())
You can create a range of numbers using np.arange(start, stop, step):

In [61]:
np.arange(0, 10, 2)  # Output: [0, 2, 4, 6, 8]


array([0, 2, 4, 6, 8])

1. Basic Arithmetic Operations
You can perform element-wise arithmetic operations on arrays:

In [64]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5, 7, 9]
print()
print(a - b) 
print()
print(a * b) 
print()
print(b / a) 
print()

[5 7 9]

[-3 -3 -3]

[ 4 10 18]

[4.  2.5 2. ]



2. Universal Functions (ufuncs)
NumPy provides mathematical functions that operate element-wise on arrays. These are called ufuncs (universal functions).

In [69]:
a=np.array([30,45,90],dtype="int64")
print(np.sqrt(a))

[5.47722558 6.70820393 9.48683298]


In [70]:
np.exp(a)  # Output: [2.71828183 7.3890561  20.08553692]


array([1.06864746e+13, 3.49342711e+19, 1.22040329e+39])

In [72]:
print(np.sin(a))# Sine of each element in 'a'
print()
np.cos(a)  # Cosine of each element in 'a'


[-0.98803162  0.85090352  0.89399666]



array([ 0.15425145,  0.52532199, -0.44807362])

3. Aggregation Functions
These functions perform operations on the entire array.

In [76]:
a=np.array([1,2,3])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

6
2.0
1
3


4. Matrix Multiplication (Dot Product)
You can multiply two arrays using the dot product:

In [77]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[7,8,9],[4,5,6],[1,2,3]])
np.dot(a, b) 

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 90, 114, 138]])

In [79]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # Output: 32 (1*4 + 2*5 + 3*6)


32


2. Matrix Determinant
For a square matrix, you can calculate the determinant:

In [80]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)  # Output: -2.0


np.float64(-2.0000000000000004)

3. Matrix Inverse
If a matrix is invertible (determinant ≠ 0), you can calculate its inverse:

In [81]:
A = np.array([[1, 2], [3, 4]])
np.linalg.inv(A)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

4. Eigenvalues and Eigenvectors
You can compute the eigenvalues and eigenvectors of a matrix:

In [87]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print("\n")
print(eigenvectors)

[-0.37228132  5.37228132]


[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


5. Solving Linear Equations
NumPy also helps to solve linear equations of the form Ax = b:

In [89]:
A = np.array([[3, 2], [1, 4]])
b = np.array([7, 10])
x = np.linalg.solve(A, b)  # Solves for x in Ax = b
print(x)

[0.8 2.3]


Let's visualize this in terms of equations.

We have:

```python
A = np.array([[3, 2],
              [1, 4]])
b = np.array([7, 10])
```

This represents the **matrix equation**:

$$
\begin{bmatrix}
3 & 2 \\
1 & 4 \\
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
\end{bmatrix}
=
\begin{bmatrix}
7 \\
10 \\
\end{bmatrix}
$$

Which means you're solving this **system of linear equations**:

$$
\begin{cases}
3x + 2y = 7 \\
x + 4y = 10 \\
\end{cases}
$$

When you use:

```python
x = np.linalg.solve(A, b)
```

NumPy gives you the solution for $x$ and $y$ that satisfies both equations.



### 🧮 **Statistics with NumPy**

NumPy provides powerful statistical functions to perform operations on arrays. Here are the most commonly used ones:

---

### 1. **Mean (Average)**

```python
np.mean(array)
```

Returns the average of all elements.

---

### 2. **Median**

```python
np.median(array)
```

Returns the middle value of the array (or average of two middle values if even number of elements).

---

### 3. **Standard Deviation**

```python
np.std(array)
```

Tells how spread out the numbers are from the mean.

---

### 4. **Variance**

```python
np.var(array)
```

Gives the average of the squared deviations from the mean.

---

### 5. **Min and Max**

```python
np.min(array)
np.max(array)
```

Returns the smallest and largest element.

---

### 6. **Sum and Product**

```python
np.sum(array)
np.prod(array)
```

Gives total sum or total product of elements.

---

### 7. **Percentile**

```python
np.percentile(array, q)
```

Returns the q-th percentile (e.g. 50 for median, 25 for Q1, 75 for Q3).

---

### 8. **Argmin and Argmax**

```python
np.argmin(array)
np.argmax(array)
```

Gives the index of the minimum or maximum element.



If your dataset is in a NumPy array format, here's how it works:

### Example:

```python
import numpy as np

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

std_all = np.std(data)
var_all = np.var(data)
```

* `np.std(data)` → gives the **standard deviation** of all elements combined.
* `np.var(data)` → gives the **variance** of all elements combined.

### Axis-wise:

If you want to apply it **row-wise or column-wise**, use the `axis` parameter:

* `np.std(data, axis=0)` → standard deviation **column-wise**
* `np.std(data, axis=1)` → standard deviation **row-wise**

Same for variance with `np.var()`.

✅ Reorganizing Arrays in NumPy
NumPy provides multiple ways to reshape and stack arrays efficiently:

📌 reshape()
Used to change the shape of an array without changing its data:

In [98]:
a = np.array([1, 2, 3, 4, 5, 6])
a=a.reshape(2, 3)
# Shape becomes (2 rows, 3 columns)
# Total elements must remain the same

📌 ravel() vs flatten()
Both convert multi-dimensional arrays to 1D.

In [99]:
a.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
# 📌 vstack() (vertical stack)
# Stacks arrays vertically (row-wise):
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
# 📌 hstack() (horizontal stack)
# Stacks arrays side-by-side (column-wise):
np.hstack((a, b))


array([1, 2, 3, 4, 5, 6])

✅ Load data from a file using NumPy

1️⃣ Using np.loadtxt() (if your CSV has only numeric data)

import numpy as np

data = np.loadtxt(r"C:\Users\user\Downloads\iris.csv", delimiter=",", skiprows=1, dtype=float)

print(data)

⚠️ If your CSV has text columns (like species names), loadtxt() will fail. Use genfromtxt() instead.



In [104]:
#this function is used becoz our dataset has different data types like numeric and non numeric 
import numpy as np

# here's the dataset link https://www.kaggle.com/datasets/himanshunakrani/iris-dataset

# Using genfromtxt for mixed data types (numeric + text)
data = np.genfromtxt(r"C:\Users\user\Downloads\iris.csv", delimiter=",", dtype=None, encoding="utf-8", skip_header=1)

print(data)


[(5.1, 3.5, 1.4, 0.2, 'setosa') (4.9, 3. , 1.4, 0.2, 'setosa')
 (4.7, 3.2, 1.3, 0.2, 'setosa') (4.6, 3.1, 1.5, 0.2, 'setosa')
 (5. , 3.6, 1.4, 0.2, 'setosa') (5.4, 3.9, 1.7, 0.4, 'setosa')
 (4.6, 3.4, 1.4, 0.3, 'setosa') (5. , 3.4, 1.5, 0.2, 'setosa')
 (4.4, 2.9, 1.4, 0.2, 'setosa') (4.9, 3.1, 1.5, 0.1, 'setosa')
 (5.4, 3.7, 1.5, 0.2, 'setosa') (4.8, 3.4, 1.6, 0.2, 'setosa')
 (4.8, 3. , 1.4, 0.1, 'setosa') (4.3, 3. , 1.1, 0.1, 'setosa')
 (5.8, 4. , 1.2, 0.2, 'setosa') (5.7, 4.4, 1.5, 0.4, 'setosa')
 (5.4, 3.9, 1.3, 0.4, 'setosa') (5.1, 3.5, 1.4, 0.3, 'setosa')
 (5.7, 3.8, 1.7, 0.3, 'setosa') (5.1, 3.8, 1.5, 0.3, 'setosa')
 (5.4, 3.4, 1.7, 0.2, 'setosa') (5.1, 3.7, 1.5, 0.4, 'setosa')
 (4.6, 3.6, 1. , 0.2, 'setosa') (5.1, 3.3, 1.7, 0.5, 'setosa')
 (4.8, 3.4, 1.9, 0.2, 'setosa') (5. , 3. , 1.6, 0.2, 'setosa')
 (5. , 3.4, 1.6, 0.4, 'setosa') (5.2, 3.5, 1.5, 0.2, 'setosa')
 (5.2, 3.4, 1.4, 0.2, 'setosa') (4.7, 3.2, 1.6, 0.2, 'setosa')
 (4.8, 3.1, 1.6, 0.2, 'setosa') (5.4, 3.4, 1.5, 0.4, 's

✅ Save a NumPy array to a file


In [109]:
np.savetxt("output.csv", data, delimiter=",", fmt="%s")
# fmt="%s" is required when saving string-type data.

1. Boolean Masking
Create a mask of True/False values by applying a condition to the array:

In [113]:
import numpy as np

# Toy dataset
data = np.array([
    [5.1, 3.5, 1.4, 0.2, "setosa"],
    [7.0, 3.2, 4.7, 1.4, "versicolor"],
    [6.3, 3.3, 6.0, 2.5, "virginica"],
    [5.8, 2.7, 5.1, 1.9, "virginica"],
    [5.0, 3.6, 1.4, 0.2, "setosa"]
], dtype=object)

# Split into numeric features and string labels
features = data[:, :4].astype(float)   # shape (5,4)
labels   = data[:, 4]                  # shape (5,)

# 1) Mask for sepal length > 5.5 (column 0)
mask_sepal = features[:, 0] > 5.5
filtered_sepal = data[mask_sepal]
print("Rows with sepal length > 5.5:\n", filtered_sepal)

# 2) Mask for species == 'setosa'
mask_setosa = labels == "setosa"
filtered_setosa = data[mask_setosa]
print("\nRows with species 'setosa':\n", filtered_setosa)


Rows with sepal length > 5.5:
 [[7.0 3.2 4.7 1.4 'versicolor']
 [6.3 3.3 6.0 2.5 'virginica']
 [5.8 2.7 5.1 1.9 'virginica']]

Rows with species 'setosa':
 [[5.1 3.5 1.4 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']]


## 1. Integer Array Indexing (“Fancy” indexing)

You can pass an array (or list) of integer indices to select those rows or columns


In [115]:
a = np.arange(12).reshape(3,4)
# a = [[ 0,  1,  2,  3],
#      [ 4,  5,  6,  7],
#      [ 8,  9, 10, 11]]

# Pick rows 0 and 2:
rows = np.array([0,2])
print(a[rows])
# -> [[ 0, 1, 2, 3],
#     [ 8, 9,10,11]]

# Pick elements at (0,1), (1,2), (2,3):
row_idx = np.array([0,1,2])
col_idx = np.array([1,2,3])
print(a[row_idx, col_idx])
# -> [1, 6, 11]

[[ 0  1  2  3]
 [ 8  9 10 11]]
[ 1  6 11]



## 2. Combined Fancy & Slicing

You can mix integer indexing with slices:


In [116]:
print(a[[0,2], 1:4:2])
# -> [[ 1, 3],
#     [ 9,11]]

[[ 1  3]
 [ 9 11]]



## 3. Using `np.ix_` for Cross-Product

If you want the full cross‑product of two index sets:

This is equivalent to picking rows 0&2 and columns 1&3 in a grid.

In [118]:
r = [0,2]
c = [1,3]
print(a[np.ix_(r,c)])
# -> [[ 1,  3],
#     [ 9, 11]]

[[ 1  3]
 [ 9 11]]


## 4. Boolean vs Fancy

* **Boolean indexing** uses a mask of True/False.
* **Fancy indexing** uses integer arrays of positions.



In [ ]:
mask = np.array([True, False, True])
# Select rows 0 & 2, then pick columns [0,2,3]:
print(a[mask][:, [0,2,3]])


## 5. Newaxis & Ellipsis

* **`np.newaxis`** lets you increase dimensions:


In [121]:
  v = np.array([1,2,3])        # shape (3,)
  v2 = v[:, np.newaxis]        # shape (3,1)
  print(v2)

[[1]
 [2]
 [3]]


* **`...` (ellipsis)** stands for “as many `:` as needed”:

In [122]:
  b = np.arange(24).reshape(2,3,4)
  b[...,2]   # equivalent to b[:,:,2]

array([[ 2,  6, 10],
       [14, 18, 22]])